# Generated by Django 5.1.15 on 2026-08-29 10:34

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        default=apps.orders.models.generate_order_number,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Confirmation"),
                            ("CONFIRMED", "Order Confirmed"),
                            ("PREPARING", "Preparing / Harvesting"),
                            ("READY", "Packed & Ready"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled by Customer"),
                            ("REJECTED", "Rejected by Farmer"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=8),
                ),
                (
                    "marketplace_commission",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("delivery_address_snapshot", models.JSONField(default=dict)),
                ("customer_notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Payment Pending"),
                            ("PAID", "Payment Received"),
                            ("REFUNDED", "Payment Refunded"),
                            ("FAILED", "Payment Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("CREDIT_CARD", "Credit / Debit Card"),
                            ("BAKONG_QR", "KHQR / Bakong"),
                            ("BANK_TRANSFER", "Direct Bank Transfer"),
                        ],
                        default="COD",
                        max_length=30,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("FARMER_DIRECT", "Direct Farmer Delivery"),
                            ("MARKETPLACE_LOGISTICS", "Marketplace Express Logistics"),
                            ("THIRD_PARTY", "Third-party Logistics Partner"),
                        ],
                        default="FARMER_DIRECT",
                        max_length=30,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("driver_name", models.CharField(blank=True, max_length=150)),
                ("driver_phone", models.CharField(blank=True, max_length=30)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery", models.DateTimeField(blank=True, null=True)),
                ("delivery_notes", models.TextField(blank=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("product_name_snapshot", models.CharField(max_length=200)),
                (
                    "product_image_snapshot",
                    models.CharField(blank=True, max_length=500),
                ),
                ("unit_snapshot", models.CharField(max_length=20)),
                (
                    "unit_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_orde_custome_c9b64a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["farmer", "status"], name="orders_orde_farmer__bab281_idx"
            ),
        ),
    ]
