# Generated by Django 5.1.15 on 2026-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_subscription_subscriptionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_rate_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Marketplace commission rate applied (e.g. 5.00%).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="farmer_payout",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Net payout payable to farmer (subtotal - commission).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="marketplace_commission",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total commission retained by platform.",
                max_digits=8,
            ),
        ),
    ]
