# Generated by Django 5.1.15 on 2026-08-29 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("farm_name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "bio",
                    models.CharField(
                        help_text="Short 1-2 sentence farm hook.", max_length=300
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        help_text="Full background story, values, and traditions."
                    ),
                ),
                (
                    "farming_practice",
                    models.CharField(
                        choices=[
                            ("ORGANIC", "Certified Organic / Natural"),
                            ("CONVENTIONAL", "Conventional Sustainable"),
                            ("HYDROPONIC", "Hydroponic / Greenhouse"),
                            ("PERMACULTURE", "Permaculture / Agroforestry"),
                            ("REGENERATIVE", "Regenerative Agriculture"),
                        ],
                        db_index=True,
                        default="ORGANIC",
                        max_length=30,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=1)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="farmers/profiles/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="farmers/covers/"
                    ),
                ),
                ("province", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                ("address_line", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("website_url", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Verified & Approved"),
                            ("REJECTED", "Verification Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        db_index=True, decimal_places=2, default=0.0, max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_verified", "-rating_avg", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmerVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "id_card_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="verifications/ids/"
                    ),
                ),
                (
                    "land_certificate_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="verifications/land/"
                    ),
                ),
                (
                    "organic_certification_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="verifications/certs/"
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_doc",
                        to="farmers.farmerprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
