# Generated by Django 5.1.15 on 2026-08-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="bakong_account_id",
            field=models.CharField(
                blank=True,
                help_text="e.g. sokha_farm@aba or 012888999@aclb",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="bank_name",
            field=models.CharField(blank=True, default="ABA Bank", max_length=100),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="farmer_qr_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="farmers/qrcodes/"
            ),
        ),
    ]
