# Generated by Django 5.1.15 on 2026-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_verify_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="customers/profiles/"
            ),
        ),
    ]
