# Generated by Django 5.0.6 on 2026-09-04 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0002_farmerprofile_bakong_account_id_and_more"),
        (
            "orders",
            "0003_order_commission_rate_percentage_order_farmer_payout_and_more",
        ),
        ("payments", "0002_processedwebhook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount paid by buyer",
                        max_digits=12,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "commission_rate_percentage",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Marketplace fee retained by platform",
                        max_digits=10,
                    ),
                ),
                (
                    "farmer_net_payout",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount credited to farmer",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("payment_method", models.CharField(max_length=30)),
                (
                    "qr_payload",
                    models.TextField(
                        blank=True, help_text="KHQR / EMVCo QR code string"
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=150)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bakong_account_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Settlement"),
                            ("SUCCESS", "Settled / Successful"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="farmers.farmerprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
