# Generated by Django 5.1.15 on 2026-08-30 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expected_harvest_date",
            field=models.DateField(
                blank=True, help_text="Expected harvest date for pre-orders", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_preorder",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if item is pre-harvest advance order",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="peak_season_months",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Months [1..12] when crop is in peak season",
            ),
        ),
        migrations.CreateModel(
            name="VolumeDiscountTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum quantity required for tier",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage discount e.g. 15.00 for 15%",
                        max_digits=5,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discounted unit price override",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_tiers",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["min_quantity"],
                "unique_together": {("product", "min_quantity")},
            },
        ),
    ]
