# Generated by Django 5.1.15 on 2026-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_expected_harvest_date_product_is_preorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="blur_placeholder",
            field=models.TextField(
                blank=True, help_text="Base64 data URI of blurred micro preview"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="medium",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/medium/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/thumbs/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
